# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-05 09:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180805_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='creat_time',
            new_name='create_time',
        ),
    ]
